### ISSUE TITLE
useInterval returns `Not all code paths return a value` error

### ISSUE THREAD

**Issue by andrewbihl** [Junscuzzy/usehooks.ts#4]
The useInterval hook does not compile as written. Currently getting: 

> Not all code paths return a value

**Comment by andrewbihl** [comment]
I assume this has to do with the compiler settings I've chosen.

For anyone else with more strict type requirements for return values, I found changing the second `useEffect` function signature to this worked: 

```
// Set up the interval.

  useEffect((): (() => void) | void => {
    function tick() {
...
```

**Comment by Junscuzzy** [comment]
Good catch thanks you! Can you share your `tsconfig.json` please, I will enforce type check more strict.
